{
 "title": "Splunk Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "index_name",
    "query": {
     "query": "label_values(splunk_exporter_index_maxTotalDataSizeMB,index_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Splunkd current global health",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "min (splunk_exporter_health{})", "legendFormat": "Splunkd" }
   ]
  },
  {
   "title": "Splunkd detailed health history",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "splunk_exporter_health{name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Indexes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Index usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "splunk_exporter_index_currentDBSizeMB{index_name=~\"$index_name\"} / splunk_exporter_index_maxTotalDataSizeMB{index_name=~\"$index_name\"}",
     "legendFormat": "{{index_name}}"
    }
   ]
  },
  {
   "title": "Index usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "splunk_exporter_index_currentDBSizeMB{index_name=~\"$index_name\"}",
     "legendFormat": "{{index_name}}"
    }
   ]
  }
 ]
}