networks:
  monitoring:

volumes:
  prometheus_data: {}

services:
  grafana:
    image: grafana/grafana-oss:10.4.3
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/:ro
    ports:
     - '3000:3000'
    expose:
      - 3000
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    expose:
      - 9090
    networks:
      - monitoring
  
  splunk_exporter:
    image: golang:1.21
    ports:
      - 9115:9115
    expose:
      - 9115
    networks:
      - monitoring
    command: sleep infinity
    # add /etc/ssl/certs/ca-certificates.crt if needed
  

  
  # splunk:
  #   image: splunk/splunk:9.2
  #   restart: unless-stopped
  #   container_name: splunk
  #   environment:
  #     - SPLUNK_START_ARGS=--accept-license
  #     - SPLUNK_PASSWORD=splunkadmin
  #   expose:
  #     - 8000
  #     - 8089
  #   ports:
  #     - 8000:8000
  #     - 8089:8089
  #   networks:
  #     - monitoring

  splunk:
    container_name: splunk
    networks:
      monitoring:
        aliases:
          - splunk
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    hostname: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_STANDALONE_URL=splunk
      - DEBUG=true
      - SPLUNK_PASSWORD=splunkadmin
    ports:
      - 8000
      - 8089

  dmc:
    container_name: dmc
    networks:
      monitoring:
        aliases:
          - dmc
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: dmc
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_STANDALONE_URL=splunk
      - SPLUNK_ROLE=splunk_monitor
      - SPLUNK_LICENSE_URI
      - SPLUNK_PASSWORD=splunkadmin
      - DEBUG=true
    ports:
      - 8000
      - 8089
