# syntax=docker/dockerfile:1

FROM golang:1.21 

ARG SRC=..
ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    # && apt-get update \
    # && apt-get install -y sudo \
    # && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    # && chmod 0440 /etc/sudoers.d/$USERNAME

# Go tooling
RUN go install -v golang.org/x/tools/gopls@latest

# Get all sources for development
WORKDIR /tmp/app
COPY ${SRC}/go.mod ${SRC}/go.mod ./
RUN go mod download


# Set the default user. Omit if you want to keep the default as root.
USER $USERNAME

# Keep the container up
CMD [ "sleep", "infinity" ]