services:
  splunk_exporter:
    restart: unless-stopped
    container_name: splunk_exporter
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile-dev
    image: splunk_exporter:latest
    ports:
      - 9115:9115
    expose:
      - 9115
    networks:
      - monitoring
    volumes:
      - ./splunk_exporter.yml:/splunk_exporter.yml:ro
    command: /splunk_exporter --config.file /splunk_exporter.yml
    # add /etc/ssl/certs/ca-certificates.crt if needed
  